### ISSUE TITLE
1.3.0 undocumented breaking changes with pascal case.

### ISSUE THREAD

**Issue by virtuallyunknown** [kristiandupont/recase#82]
This is best explained with a piece of code:

```js
import { recase } from '@kristiandupont/recase';

function toPascalCase(name) {
    return recase('snake', 'pascal')(name);
}

// version 1.2.1
console.log(toPascalCase(`FOObar_baz`));
// outputs: FOObarBaz

// version 1.3.0
console.log(toPascalCase(`FOObar_baz`));
// outputs: FoobarBaz
```

So in version `1.2.1`, given `FOObar_baz` as input, the pascal case function returns `FOObarBaz`, but in the latest version, it returns `FoobarBaz`.

I don't know if this is intentional or not, but given that the library seems to have around ~20k weekly downloads, it might be a good idea to document this or deprecate 1.3.0.

Cheers!

**Comment by kristiandupont** [comment]
That is not intentional, sorry about that! It does give me pause though -- you could argue that either is correct.. I wonder if there should be an option or something..

**Comment by virtuallyunknown** [comment]
If the intention is to keep things as simple as possible, then adding extra options might introduce some complexity to your library which might make it harder to maintain in the long run. On the other hand, if the library doesn't require super active development then maybe it's not a big deal, I'm not sure to be honest.

I found a similar library to yours that deals with camel case exclusively, and it accepts an options object as a parameter, and one of the options is `preserveConsecutiveUppercase: boolean`, so in case you're looking for ideas or inspiration something like that might work.

**Comment by kristiandupont** [comment]
I decided to just revert for now, so no need for options. Let me know if you have further issues!
